import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/Utils/ReactQuery/QueryProvider";
import { ThemeProvider } from "@/components/useThemes/provider";
import ToastProvider from "@/Utils/Toast/ToastProvider";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryProvider>
          <ThemeProvider>
 {children}
 <ToastProvider/>
          </ThemeProvider>
        
        </QueryProvider>
      </body>
    </html>
  );
}
